Add flagging functions for power spectra
HERA-Team/hera_pspec pull request #157
Opened 2018-07-13 22:38 UTC by shaunakmodak

Functions for generating greedy flagging masks, consolidating LST binned NSamples & Flag data into numpy arrays, and plotting visualizations of the flagging.

2018-07-14 06:35 UTC, philbull requested changes
Review of in-progress PR.

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +    axis : int
This would be better off as a string, and maybe with a name change, e.g. `first='row'`.

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +        binary array with 1 representing flagged, 0 representing unflagged
Is this the same as the output of `UVData.get_flags()`, or does that need to be modified in some way before passing it to this function?

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +    Generates a greedy flags mask from input flags and nsamples arrays
I think it's worth briefly explaining how the algorithm works here.

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +    greedy : bool
What if it's False?

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +mask_generator(nsamples, flags, n_threshold, greedy=False, axis, greedy_threshold, retain_flags=True):
Maybe a more descriptive function name, e.g. `construct_factorizable_mask`?

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +        LST-Bin Flags are left flagged even if thresholds are not met (default is True)
The data going into this are not necessarily LST binned.

2018-07-14 06:35 UTC, philbull commented on hera_pspec/flags.py
> +    for i in range(shape[0]):
Can this nested `for` loop perhaps be replaced by a couple of strategic calls to `np.where`? We can discuss this.

2018-07-15 10:12 UTC, nkern commented
Have either of you seen the development in `PSpecData.broadcast_dset_flags`? Seems like there is some possible overlap in what these two are trying to accomplish. Perhaps some of the code in `broadcast_dset_flags` should be put in `flags.py` and `broadcast_dset_flags` should then call routines in `flags.py`...

2019-07-10 09:08 UTC, philbull commented
I've moved most of the code from this PR into `hera_stats`, where it will be very useful for testing different ways of flagging the data. The relevant PR is here: https://github.com/HERA-Team/hera_stats/pull/22

This code could have lived in `hera_pspec` too, but I think it's worth trying to limit the number of peripheral features in pspec and keep it more or less focused on its core function (it's complicated enough). `hera_stats` is supposed to be a bigger tent, covering many different aspects of the analysis, so I think it's appropriate to move this there.

2019-07-10 09:08 UTC, closed without merging