Switch test suite to pytest
HERA-Team/hera_pspec pull request #312
Opened 2021-03-17 15:56 UTC by philbull

Converts the existing unit tests to use pytest instead of nosetests.

2021-03-17 20:46 UTC, philbull commented
Note that the behaviour of `hera_pspec.pspecdata.trim_dset_lsts()` has now changed; a `ValueError` is now raised if the datasets aren't aligned.

2021-03-18 09:21 UTC, philbull commented
Now addresses #280 and #288

2021-04-07 00:15 UTC, saurabh-astro requested changes
Thanks for this much needed switch. I have left a few comments to do with dependencies, and a couple of tests. This already looks great!

2021-04-08 12:30 UTC, philbull commented on hera_pspec/tests/test_pspecdata.py
> +        assert ds.dsets[1].Ntimes == 50 #52
It's unclear, and I haven't been able to figure it out. I suspect something upstream has changed, but this could use closer scrutiny...

2021-04-08 13:40 UTC, philbull commented on hera_pspec/tests/test_pspecdata.py
> +        #assert ds.dsets[1].Ntimes == 60
Not sure why I'd commented this out -- I've reinstated it.

2021-04-08 13:41 UTC, philbull commented on hera_pspec/pspecbeam.py
> +        for key in list(OmegaPP.keys()):
This particular change isn't strictly necessary, but there are other bits where the Python 2->3 handling of the `.keys()` iterator changed and so casting it as a list was necessary.

2021-04-08 13:42 UTC, philbull commented on hera_pspec/tests/test_uvpspec_utils.py
> +    assert isinstance(blps[0][0], (np.int, int)) == True
Good catch, this was just an artefact of converting from the old style.

2021-04-08 13:43 UTC, philbull commented on hera_pspec/tests/test_utils.py
> +        assert len(bls1) == len(bls2), 15
Yep, good catch

2021-04-18 20:00 UTC, nkern commented
@philbull @saurabh-astro update on the problem with the unittest for `trim_dset_lsts`:

turns out there was a bug in the old test: 50 is the right number, but it was being checked as `assert_true(Ntimes, 52)`, which returns True b/c both are non-zero, not because they are equal.

2021-04-18 20:02 UTC, nkern commented on hera_pspec/tests/test_pspecdata.py
> +        assert ds.dsets[1].Ntimes == 50 #52
see below

2021-04-18 20:05 UTC, nkern approved these changes

2021-04-18 20:07 UTC, nkern commented
@philbull lets wait to merge until @saurabh-astro lets us know if he has any further comments on this--also macos 3.8 seems to be failing due to an h5py import error--seems like it's github's fault though, not ours?

2021-04-18 21:06 UTC, saurabh-astro commented
> @philbull lets wait to merge until @saurabh-astro lets us know if he has any further comments on this--also macos 3.8 seems to be failing due to an h5py import error--seems like it's github's fault though, not ours?

Great, thanks Nick! I have gone through rest of the changes, and it all seems fine to me. Good to go @philbull!

2021-04-29 16:48 UTC, merged