Expanded Correlation Selection Options.
HERA-Team/hera_pspec pull request #340
Opened 2021-05-04 22:49 UTC by aewallwi

Options to select cross-correlations and autocorrelations in power spectrum with new args `include_autocorrs` and `exclude_crosscorrs` in `pspec_run`.

2021-05-04 23:10 UTC, aewallwi commented on hera_pspec/grouping.py
> +        uvp_list = uvpspec_utils.select_common(uvp_list, spws=True,
This miss was caused by white space removal.

2021-08-20 17:16 UTC, jsdillon requested changes
Seems basically fine. Just a handful of minor issues, mostly with documentation.

2021-08-20 17:16 UTC, jsdillon commented on scripts/generate_pstokes_run.py
> +uvd_output.write_uvh5(args.outputdata, clobber=args.clobber)
Why did you remove the newline?

2021-08-20 17:16 UTC, jsdillon commented on hera_pspec/utils.py
> +
This whitespace doesn't seem standard.

2021-08-21 17:58 UTC, aewallwi commented on hera_pspec/grouping.py
> +        # using the bootstrap-sampled blpair weights
This must be a merge artifact. Thanks for catching! I've deleted this.

2021-08-21 18:01 UTC, aewallwi commented on hera_pspec/pspecdata.py
> +    xant_flag_thresh : float, optional
Maybe I selected the wrong rebase option? Fixed!

2021-08-21 18:03 UTC, aewallwi commented on scripts/generate_pstokes_run.py
> +uvd_output.write_uvh5(args.outputdata, clobber=args.clobber)
Not sure. I've put it back in.

2021-08-21 18:03 UTC, aewallwi commented on hera_pspec/utils.py
> +
I think this has been standardized now.

2021-08-21 18:13 UTC, aewallwi commented
Thanks for the timely review @jsdillon. I think this is ready for another look when you have a chance!

2021-08-22 16:49 UTC, jsdillon approved these changes

2021-08-22 22:26 UTC, merged