Add extract autos script
HERA-Team/hera_pspec pull request #393
Opened 2024-02-09 12:50 UTC by mwilensky768

I'm not sure if this script belongs in pspec but basically in the face of fringe rate filtering it will be a huge speedup to have the autos extracted to their own waterfall file after LST binning for the sake of noise error propagation and any other post-LST-binning analysis that might be fun to do on the autos.

I've added a script that does the extraction with basic UVData operations. I also added an argument parser for this script in utils, with associated unit test.

2024-02-09 12:51 UTC, mwilensky768 commented
I have not yet tested that this script actually runs, but I've done parts of it in a jupyter notebook. I will update this PR when I have actually checked the script.

2024-02-14 18:23 UTC, r-pascua requested changes
This is looking good! I left a few comments, but the only thing I feel really strongly about is the silent passing in lines 38-39, which I think needs to have a more explicit warning (or just a straight up failure).

On a different note, I feel like `hera_pspec` is the wrong place for this script. I would argue that this should maybe go somewhere in `hera_pipelines`, for lack of a better place to put it. Curious to hear thoughts from other people, though.

2024-02-14 18:23 UTC, r-pascua commented on scripts/extract_autos_post_lstbin.py
> +        main_uvd.write_uvh5(outfile, clobber=True)
I think for best practice, `clobber` should be an argument passed to the script.

2024-02-14 18:23 UTC, r-pascua commented on scripts/extract_autos_post_lstbin.py
> +            continue
I found this block of code a little difficult to parse at first--it took me a few reads to wrap my head around it. I would maybe instead add a comment to the effect of "Find the first file that has autos."

2024-02-14 18:23 UTC, r-pascua commented on scripts/extract_autos_post_lstbin.py
> +            for file in args.flist[file_ind + 1:]:
I'm not sure how important it is to track whether only one file had autocorrelations in it, but if it's not that important to do, then you can replace this block with:
`for file in args.flist[file_ind + 1:]`
If `file_ind + 1` is greater than `len(args.flist)`, this just doesn't do any iterations.

2024-02-14 18:23 UTC, r-pascua commented on scripts/extract_autos_post_lstbin.py
> +                    continue
This worries me. Are you certain the only way a `ValueError` can be raised is by a file not having autos in it? What if the autos in one file differ from the autos in a different file? I'd think that `pyuvdata` would also have an issue with that. At any rate, I think something like `warnings.warn("Some files missing autos")` should be emitted before continuing.

2024-02-14 18:23 UTC, r-pascua commented on scripts/extract_autos_post_lstbin.py
> +                    main_uvd.__add__(new_uvd, inplace=True)
I'd suggest adding an `axis` argument to the parser, which defaults to `None`, that will let you do fast concatenation here by specifying `axis=args.axis`. Our typical use case should let us use `axis='blt'` to speed up the concatenation.

2024-03-11 16:13 UTC, mwilensky768 commented
Closing since this all lives in `hera_pipelines` now.

2024-03-11 16:13 UTC, closed without merging